MODEL:
  
  BACKBONE: 'effnetb4'
  NAME: 'effb4_SVMeta'
  
  IMG_FCS:  [3584,512]
DATASETS:
  ROOT_DIR: ['../data/all18_coloradj']
  DICT_LABEL: ['MEL', 'NV', 'BCC', 'AK', 'BKL', 'DF', 'VASC','SCC','UNK'] 
  INFO_CSV: ['./dat/all19_info1_unk.csv']
  NUM_CLASS: 9
  
DATALOADER:
  BATCH_SIZE: 12
TEST:
  BATCH_SIZE: 32
  
SOLVER:
  EPOCHS: 80

MISC:
  OUT_DIR: "../checkpoint/effb4_meta_default_19_unk"
  VALID_EPOCH: 10