MODEL:
  
  BACKBONE: 'effnetb4'
  NAME: 'effb4_SingleView'
  
  IMG_FCS:  [3584,512]
DATASETS:
  DICT_LABEL: ['MEL', 'NV', 'BCC', 'AK', 'BKL', 'DF', 'VASC','SCC'] 
  ROOT_DIR: [ '../data/all19_usp_coloradj']
  INFO_CSV: ['./dat/all19_info_test.csv']
  
  NUM_CLASS: 8
  
DATALOADER:
  BATCH_SIZE: 12
TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/effb4_default_19"
  VALID_EPOCH: 10
  TTA_MODE: 'mean_softmax' #'mean' 'gmean' 'mean_softmax'  
  
  
  
  
  
  
