MODEL:
  BACKBONE: 'effnetb4'
  NAME: 'effb4_SVMeta_SSL'

  SSL_FIXMATCH: True
  PSEUDO_TH: 0.95
  IMG_FCS:  [3584,512]


DATASETS:
  ROOT_DIR:  ['../data/all18_usp_coloradj']
  INFO_CSV: ['./dat/all18_info_test.csv']


TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/effb4_meta_SSL"
  VALID_EPOCH: 5
