MODEL:

  BACKBONE: 'effnetb4'
  NAME: 'effb4_SVMeta_SSL'

  SSL_FIXMATCH: True
  PSEUDO_TH: 0.95
  IMG_FCS:  [3584,512]
DATASETS:
  ROOT_DIR:  ['../data/all18_coloradj'  , '../data/all19_usp_coloradj']
  INFO_CSV:  ['./dat/all18_info.csv', './dat/all19_info_usp.csv']


DATALOADER:
  BATCH_SIZE: 12
TEST:
  BATCH_SIZE: 32
  
SOLVER:
  EPOCHS: 60

MISC:
  OUT_DIR: "../checkpoint/effb4_meta_SSL"
  VALID_EPOCH: 10
  LOG_PERIOD: 10000