MODEL:
  
  BACKBONE: 'effnetb4'
  NAME: 'effb4_SVMeta'
  
  IMG_FCS:  [3584,512]
  META_DIMS: [17,6,1,3,2]

DATALOADER:
  BATCH_SIZE: 12
  SAMPLER: 'weighted_meta'
  NUM_WORKERS: 8
  
DATASETS:
  ROOT_DIR:  ['../data/all18_usp_coloradj']
  INFO_CSV: ['./dat/all18_info_test.csv']
  META_LIST: ['age','pos','sex','color_gain','kpds']
TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/effb4_meta_default_d_pos"
  VALID_EPOCH: 10
  LOG_PERIOD: 10000
  
INPUT: 
  CRP_SCALE: [0.1,1.0]
  CRP_RATIO: [0.75,1.33]
