MODEL:
  
  BACKBONE: 'effnetb4'
  NAME: 'effb4_SVMeta'
  LOSS_TYPE: 'focalloss'
  IMG_FCS:  [3584,512]
DATASETS:
  DICT_LABEL: ['MEL', 'NV', 'BCC', 'AK', 'BKL', 'DF', 'VASC','SCC'] 
  INFO_CSV: ['./dat/all19_info1.csv']
  NUM_CLASS: 8
DATALOADER:
  BATCH_SIZE: 12
  SAMPLER: 'weighted_meta'
  NUM_WORKERS: 8
TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/effb4_meta_default19_fl_d"
  VALID_EPOCH: 10
  LOG_PERIOD: 10000
  
INPUT: 
  CRP_SCALE: [0.1,1.0]
  CRP_RATIO: [0.75,1.33]
