MODEL:
  
  BACKBONE: 'effnetb3'
  NAME: 'effb3_SVMeta'
  
  IMG_FCS:  [3072,512]
  META_DIMS: [17,6,1,3,2]
  
  
DATASETS:
  ROOT_DIR: ['../data/all18_coloradj','../data/all20_coloradj']
  DICT_LABEL: ['NV', 'MEL'] 
  INFO_CSV: ['./dat/all18_info1_convert20.csv','./dat/all20_info1.csv']
  NUM_CLASS: 2
  META_POS: ['head/neck','upper extremity','lower extremity','torso','palms/soles','oral/genital']

  META_LIST: ['age','pos','sex','color_gain','kpds']
  OUT_AUGPOS: True

DATALOADER:
  BATCH_SIZE: 16
  SAMPLER: 'weighted_meta'
  NUM_WORKERS: 8
TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/effb3_meta_default20_d_metafix_pos"
  VALID_EPOCH: 10
  LOG_PERIOD: 10000
  
INPUT: 
  SIZE_TRAIN_IN: [300,300]
  CRP_SCALE: [0.1,1.0]
  CRP_RATIO: [0.75,1.33]
SOLVER:
  EPOCHS: 50