MODEL:

  NAME: 'effb4_SingleView'
  BACKBONE: 'effnetb4'


  LOSS_TYPE: 'pcs'
  IMG_FCS:  [3584,512]
DATALOADER:
  BATCH_SIZE: 8
TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/effb4_pcs"
  VALID_EPOCH: 1

  LOG_PERIOD: 1000