MODEL:
  
  BACKBONE: 'effnetb4'
  NAME: 'effb4_SVMeta'
  
  IMG_FCS:  [3584,512]

DATASETS:
  ROOT_DIR:  ['../data/all18_usp_coloradj']
  INFO_CSV: ['./dat/all18_info_test.csv']

DATALOADER:
  BATCH_SIZE: 12
TEST:
  BATCH_SIZE: 32

SOLVER:
  EPOCHS: 80
MISC:
  OUT_DIR: "../checkpoint/effb4_meta_default1"
  VALID_EPOCH: 10
  TTA_MODE: 'mean' #'mean' 'gmean' 'mean_softmax' 