MODEL:
  NAME: 'effb4_SingleView'
  BACKBONE: 'effnetb4'

  IMG_FCS:  [3584,512]

DATALOADER:
  BATCH_SIZE: 2
TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/effb4_default_d"
  VALID_EPOCH: 10
  LOG_PERIOD: 1