MODEL:
  
  BACKBONE: 'effnetb3'
  NAME: 'effb3_SVMeta'
  LOSS_TYPE: 'focalloss'
  IMG_FCS:  [3072,512]
DATASETS:
  DICT_LABEL: ['MEL', 'NV', 'BCC', 'AK', 'BKL', 'DF', 'VASC','SCC'] 
  INFO_CSV: ['./dat/all19_info_test.csv']
  NUM_CLASS: 8

  ROOT_DIR:  ['../data/all19_usp_coloradj']

DATALOADER:
  BATCH_SIZE: 16
  SAMPLER: 'weighted_meta'
  NUM_WORKERS: 8
TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/effb3_meta_default19_fl_d"
  VALID_EPOCH: 10
  LOG_PERIOD: 10000
  TTA_MODE: 'mean_softmax' #'mean' 'gmean' 'mean_softmax' 
  
INPUT: 
  SIZE_TRAIN_IN: [300,300]
  CRP_SCALE: [0.1,1.0]
  CRP_RATIO: [0.75,1.33]
