MODEL:
  
  BACKBONE: 'effnetb4'
  NAME: 'effb4_SVMeta'
  
  IMG_FCS:  [3584,512]
  META_DIMS: [17,6,1,3,2]
DATASETS:
  ROOT_DIR: ['../data/all20_usp_coloradj']
  DICT_LABEL: ['NV', 'MEL'] 
  INFO_CSV: ['./dat/all20_info_usp.csv']
  NUM_CLASS: 2
  META_POS: ['head/neck','upper extremity','lower extremity','torso','palms/soles','oral/genital']
  
DATALOADER:
  BATCH_SIZE: 12
  SAMPLER: 'weighted_meta'
  NUM_WORKERS: 8
TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/effb4_meta_default20_d_metafix"
  VALID_EPOCH: 10
  LOG_PERIOD: 10000
  
INPUT: 
  CRP_SCALE: [0.1,1.0]
  CRP_RATIO: [0.75,1.33]
SOLVER:
  EPOCHS: 50