MODEL:
  
  BACKBONE: 'resnet50'
  NAME: 'resnet50_SVMeta'
  
  IMG_FCS:  [4096,512]
DATASETS:
  DICT_LABEL: ['MEL', 'NV', 'BCC', 'AK', 'BKL', 'DF', 'VASC','SCC'] 

  NUM_CLASS: 8
  ROOT_DIR:  '../data/all19_usp_coloradj'
  INFO_CSV: './dat/all19_info_test.csv'
  
DATALOADER:
  BATCH_SIZE: 16
TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/resnet50_meta_default_19"
  VALID_EPOCH: 10
  TTA_MODE: 'mean'