MODEL:
  NAME: "resnet50_SVAtt"

  
  LOSS_ATT: True
  ATT_PARTS: 32
  MIXUP: True
  MIXUP_MODE: 'cutmix'
  POOLMODE: 'avg'
  MIXUP_PROB:  0.5

DATASETS:
  NAMES: 'bird'
  NUM_CLASS: 200
DATALOADER:
  BATCH_SIZE: 8
  NUM_WORKERS: 4
INPUT:
  SIZE_TRAIN_PRED: [448,448]

TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/resnet50_SVAtt_bird_cutmix_avg"
  VALID_EPOCH: 1
  LOG_PERIOD: 1000
  
  
  

  
  