MODEL:
  NAME: "resnet50_SVAtt"
  BACKBONE_PRETRAIN_PATH: '../models/resnet50-19c8e357.pth'
  
  LOSS_ATT: True
  ATT_PARTS: 32


DATASETS:
  NAMES: 'flower'
  NUM_CLASS: 102
DATALOADER:
  BATCH_SIZE: 8
  NUM_WORKERS: 4
INPUT:
  SIZE_TRAIN_PRED: [448,448]

TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/resnet50_SVAtt_flower"
  VALID_EPOCH: 1
  LOG_PERIOD: 1000