MODEL:
  
  BACKBONE: 'resnest50'
  NAME: 'resnest50_SVMeta'
  
  IMG_FCS:  [4096,512]

DATALOADER:
  BATCH_SIZE: 16
  SAMPLER: 'weighted_meta'
TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/resnest50_meta_default_d"
  VALID_EPOCH: 10
  LOG_PERIOD: 10000
  
INPUT: 
  CRP_SCALE: [0.1,1.0]
  CRP_RATIO: [0.75,1.33]
