MODEL:
  NAME: 'resnet50_SVMeta' # single view with meta
  BACKBONE_PRETRAIN_PATH: '../models/resnet50-19c8e357.pth'




TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/resnet50_meta"
  VALID_EPOCH: 5
