MODEL:
  NAME: "resnet50_SVDB"
  BACKBONE_PRETRAIN_PATH: '../models/resnet50-19c8e357.pth'

  DB_PEAKDROP: 0.5

  DB_PATCHDROP: 0.25

  DB_PATCHG: 2 
  
  DB_ALPHA: 0.1

DATALOADER:
  BATCH_SIZE: 16

TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/resnet50_SVDB"
  VALID_EPOCH: 5
  LOG_PERIOD: 1000