MODEL:

  BACKBONE_PRETRAIN_PATH: '../models/resnet50-19c8e357.pth'


  LOSS_TYPE: 'pcs'
DATALOADER:
  BATCH_SIZE: 16
TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/resnet50_pcs"
  VALID_EPOCH: 1

  LOG_PERIOD: 1000