MODEL:
  NAME: "resnet50_SingleView"

  MIXUP: True
  MIXUP_MODE: 'cutmix'
  POOLMODE: 'avg'

DATASETS:
  NAMES: 'bird'
  NUM_CLASS: 200
DATALOADER:
  BATCH_SIZE: 16
INPUT:
  SIZE_TRAIN_PRED: [448,448]

TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/resnet50_SV_bird_cutmix_ave"
  VALID_EPOCH: 1
  LOG_PERIOD: 1000
  
  
  
  
  
