MODEL:
  NAME: "resnet50_SingleView"
  BACKBONE_PRETRAIN_PATH: '../models/resnet50-19c8e357.pth'
  


DATASETS:
  NAMES: 'bird'
  NUM_CLASS: 200
DATALOADER:
  BATCH_SIZE: 16
INPUT:
  SIZE_TRAIN_PRED: [448,448]

TEST:
  BATCH_SIZE: 32

MISC:
  OUT_DIR: "../checkpoint/resnet50_SV_bird"
  VALID_EPOCH: 1
  LOG_PERIOD: 1000