MODEL:
  
  BACKBONE: 'resnet101bit'
  NAME: 'resne101tbit_SVMeta'
  
  IMG_FCS:  [4096,512]

DATALOADER:
  BATCH_SIZE: 12
  SAMPLER: 'weighted_meta'
TEST:
  BATCH_SIZE: 32
DATASETS:
  ROOT_DIR:  ['../data/all18_usp_coloradj']
  INFO_CSV: ['./dat/all18_info_test.csv']
MISC:
  OUT_DIR: "../checkpoint/resnet101bit_meta_default_d"
  VALID_EPOCH: 10
  LOG_PERIOD: 10000
  
INPUT: 
  CRP_SCALE: [0.1,1.0]
  CRP_RATIO: [0.75,1.33]
